version: '3'
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - pet-project

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - pet-project

volumes:
  api:
  postgres:

networks:
  pet-project:
    driver: bridge