version: '3.8'

services:
  auth-service:
    container_name: auth-service
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8081:8081"
    volumes:
      - ./auth-service:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0

  auth-db:
    container_name: auth-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5433:5433"
    volumes:
      - auth-db:/var/lib/postgresql/data

  blog-service:
    container_name: blog-service
    build: ./blog-service
    env_file:
      - ./blog-service/.env
    ports:
      - "8080:8080"
    volumes:
      - ./blog-service:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0

  blog-db:
    container_name: blog-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - blog-db:/var/lib/postgresql/data

volumes:
  auth-db:
  blog-db:
